/*
 * static_model.h
 *
 * automatically generated from ./GAS1.icd
 */

#ifndef STATIC_MODEL_H_
#define STATIC_MODEL_H_

#include <stdlib.h>
#include "iec61850_model.h"

extern IedModel iedModel;
extern LogicalDevice iedModel_CTRL;
extern LogicalNode   iedModel_CTRL_SIMG1;
extern DataObject    iedModel_CTRL_SIMG1_Beh;
extern DataAttribute iedModel_CTRL_SIMG1_Beh_stVal;
extern DataAttribute iedModel_CTRL_SIMG1_Beh_q;
extern DataAttribute iedModel_CTRL_SIMG1_Beh_t;
extern DataObject    iedModel_CTRL_SIMG1_InsAlm;
extern DataAttribute iedModel_CTRL_SIMG1_InsAlm_stVal;
extern DataAttribute iedModel_CTRL_SIMG1_InsAlm_q;
extern DataAttribute iedModel_CTRL_SIMG1_InsAlm_t;
extern DataObject    iedModel_CTRL_SIMG1_Pres;
extern DataAttribute iedModel_CTRL_SIMG1_Pres_mag;
extern DataAttribute iedModel_CTRL_SIMG1_Pres_mag_f;
extern DataAttribute iedModel_CTRL_SIMG1_Pres_q;
extern DataAttribute iedModel_CTRL_SIMG1_Pres_t;
extern DataObject    iedModel_CTRL_SIMG1_PresAlm;
extern DataAttribute iedModel_CTRL_SIMG1_PresAlm_stVal;
extern DataAttribute iedModel_CTRL_SIMG1_PresAlm_q;
extern DataAttribute iedModel_CTRL_SIMG1_PresAlm_t;
extern LogicalNode   iedModel_CTRL_SIMG2;
extern DataObject    iedModel_CTRL_SIMG2_Beh;
extern DataAttribute iedModel_CTRL_SIMG2_Beh_stVal;
extern DataAttribute iedModel_CTRL_SIMG2_Beh_q;
extern DataAttribute iedModel_CTRL_SIMG2_Beh_t;
extern DataObject    iedModel_CTRL_SIMG2_InsAlm;
extern DataAttribute iedModel_CTRL_SIMG2_InsAlm_stVal;
extern DataAttribute iedModel_CTRL_SIMG2_InsAlm_q;
extern DataAttribute iedModel_CTRL_SIMG2_InsAlm_t;
extern DataObject    iedModel_CTRL_SIMG2_Pres;
extern DataAttribute iedModel_CTRL_SIMG2_Pres_mag;
extern DataAttribute iedModel_CTRL_SIMG2_Pres_mag_f;
extern DataAttribute iedModel_CTRL_SIMG2_Pres_q;
extern DataAttribute iedModel_CTRL_SIMG2_Pres_t;
extern DataObject    iedModel_CTRL_SIMG2_PresAlm;
extern DataAttribute iedModel_CTRL_SIMG2_PresAlm_stVal;
extern DataAttribute iedModel_CTRL_SIMG2_PresAlm_q;
extern DataAttribute iedModel_CTRL_SIMG2_PresAlm_t;
extern LogicalNode   iedModel_CTRL_SIMG3;
extern DataObject    iedModel_CTRL_SIMG3_Beh;
extern DataAttribute iedModel_CTRL_SIMG3_Beh_stVal;
extern DataAttribute iedModel_CTRL_SIMG3_Beh_q;
extern DataAttribute iedModel_CTRL_SIMG3_Beh_t;
extern DataObject    iedModel_CTRL_SIMG3_InsAlm;
extern DataAttribute iedModel_CTRL_SIMG3_InsAlm_stVal;
extern DataAttribute iedModel_CTRL_SIMG3_InsAlm_q;
extern DataAttribute iedModel_CTRL_SIMG3_InsAlm_t;
extern DataObject    iedModel_CTRL_SIMG3_Pres;
extern DataAttribute iedModel_CTRL_SIMG3_Pres_mag;
extern DataAttribute iedModel_CTRL_SIMG3_Pres_mag_f;
extern DataAttribute iedModel_CTRL_SIMG3_Pres_q;
extern DataAttribute iedModel_CTRL_SIMG3_Pres_t;
extern DataObject    iedModel_CTRL_SIMG3_PresAlm;
extern DataAttribute iedModel_CTRL_SIMG3_PresAlm_stVal;
extern DataAttribute iedModel_CTRL_SIMG3_PresAlm_q;
extern DataAttribute iedModel_CTRL_SIMG3_PresAlm_t;
extern LogicalNode   iedModel_CTRL_SIMG4;
extern DataObject    iedModel_CTRL_SIMG4_Beh;
extern DataAttribute iedModel_CTRL_SIMG4_Beh_stVal;
extern DataAttribute iedModel_CTRL_SIMG4_Beh_q;
extern DataAttribute iedModel_CTRL_SIMG4_Beh_t;
extern DataObject    iedModel_CTRL_SIMG4_InsAlm;
extern DataAttribute iedModel_CTRL_SIMG4_InsAlm_stVal;
extern DataAttribute iedModel_CTRL_SIMG4_InsAlm_q;
extern DataAttribute iedModel_CTRL_SIMG4_InsAlm_t;
extern DataObject    iedModel_CTRL_SIMG4_Pres;
extern DataAttribute iedModel_CTRL_SIMG4_Pres_mag;
extern DataAttribute iedModel_CTRL_SIMG4_Pres_mag_f;
extern DataAttribute iedModel_CTRL_SIMG4_Pres_q;
extern DataAttribute iedModel_CTRL_SIMG4_Pres_t;
extern DataObject    iedModel_CTRL_SIMG4_PresAlm;
extern DataAttribute iedModel_CTRL_SIMG4_PresAlm_stVal;
extern DataAttribute iedModel_CTRL_SIMG4_PresAlm_q;
extern DataAttribute iedModel_CTRL_SIMG4_PresAlm_t;
extern LogicalNode   iedModel_CTRL_SIMG5;
extern DataObject    iedModel_CTRL_SIMG5_Beh;
extern DataAttribute iedModel_CTRL_SIMG5_Beh_stVal;
extern DataAttribute iedModel_CTRL_SIMG5_Beh_q;
extern DataAttribute iedModel_CTRL_SIMG5_Beh_t;
extern DataObject    iedModel_CTRL_SIMG5_InsAlm;
extern DataAttribute iedModel_CTRL_SIMG5_InsAlm_stVal;
extern DataAttribute iedModel_CTRL_SIMG5_InsAlm_q;
extern DataAttribute iedModel_CTRL_SIMG5_InsAlm_t;
extern DataObject    iedModel_CTRL_SIMG5_Pres;
extern DataAttribute iedModel_CTRL_SIMG5_Pres_mag;
extern DataAttribute iedModel_CTRL_SIMG5_Pres_mag_f;
extern DataAttribute iedModel_CTRL_SIMG5_Pres_q;
extern DataAttribute iedModel_CTRL_SIMG5_Pres_t;
extern DataObject    iedModel_CTRL_SIMG5_PresAlm;
extern DataAttribute iedModel_CTRL_SIMG5_PresAlm_stVal;
extern DataAttribute iedModel_CTRL_SIMG5_PresAlm_q;
extern DataAttribute iedModel_CTRL_SIMG5_PresAlm_t;
extern LogicalNode   iedModel_CTRL_SIMG6;
extern DataObject    iedModel_CTRL_SIMG6_Beh;
extern DataAttribute iedModel_CTRL_SIMG6_Beh_stVal;
extern DataAttribute iedModel_CTRL_SIMG6_Beh_q;
extern DataAttribute iedModel_CTRL_SIMG6_Beh_t;
extern DataObject    iedModel_CTRL_SIMG6_InsAlm;
extern DataAttribute iedModel_CTRL_SIMG6_InsAlm_stVal;
extern DataAttribute iedModel_CTRL_SIMG6_InsAlm_q;
extern DataAttribute iedModel_CTRL_SIMG6_InsAlm_t;
extern DataObject    iedModel_CTRL_SIMG6_Pres;
extern DataAttribute iedModel_CTRL_SIMG6_Pres_mag;
extern DataAttribute iedModel_CTRL_SIMG6_Pres_mag_f;
extern DataAttribute iedModel_CTRL_SIMG6_Pres_q;
extern DataAttribute iedModel_CTRL_SIMG6_Pres_t;
extern DataObject    iedModel_CTRL_SIMG6_PresAlm;
extern DataAttribute iedModel_CTRL_SIMG6_PresAlm_stVal;
extern DataAttribute iedModel_CTRL_SIMG6_PresAlm_q;
extern DataAttribute iedModel_CTRL_SIMG6_PresAlm_t;
extern LogicalNode   iedModel_CTRL_SIMG7;
extern DataObject    iedModel_CTRL_SIMG7_Beh;
extern DataAttribute iedModel_CTRL_SIMG7_Beh_stVal;
extern DataAttribute iedModel_CTRL_SIMG7_Beh_q;
extern DataAttribute iedModel_CTRL_SIMG7_Beh_t;
extern DataObject    iedModel_CTRL_SIMG7_InsAlm;
extern DataAttribute iedModel_CTRL_SIMG7_InsAlm_stVal;
extern DataAttribute iedModel_CTRL_SIMG7_InsAlm_q;
extern DataAttribute iedModel_CTRL_SIMG7_InsAlm_t;
extern DataObject    iedModel_CTRL_SIMG7_Pres;
extern DataAttribute iedModel_CTRL_SIMG7_Pres_mag;
extern DataAttribute iedModel_CTRL_SIMG7_Pres_mag_f;
extern DataAttribute iedModel_CTRL_SIMG7_Pres_q;
extern DataAttribute iedModel_CTRL_SIMG7_Pres_t;
extern DataObject    iedModel_CTRL_SIMG7_PresAlm;
extern DataAttribute iedModel_CTRL_SIMG7_PresAlm_stVal;
extern DataAttribute iedModel_CTRL_SIMG7_PresAlm_q;
extern DataAttribute iedModel_CTRL_SIMG7_PresAlm_t;
extern LogicalNode   iedModel_CTRL_SIMG8;
extern DataObject    iedModel_CTRL_SIMG8_Beh;
extern DataAttribute iedModel_CTRL_SIMG8_Beh_stVal;
extern DataAttribute iedModel_CTRL_SIMG8_Beh_q;
extern DataAttribute iedModel_CTRL_SIMG8_Beh_t;
extern DataObject    iedModel_CTRL_SIMG8_InsAlm;
extern DataAttribute iedModel_CTRL_SIMG8_InsAlm_stVal;
extern DataAttribute iedModel_CTRL_SIMG8_InsAlm_q;
extern DataAttribute iedModel_CTRL_SIMG8_InsAlm_t;
extern DataObject    iedModel_CTRL_SIMG8_Pres;
extern DataAttribute iedModel_CTRL_SIMG8_Pres_mag;
extern DataAttribute iedModel_CTRL_SIMG8_Pres_mag_f;
extern DataAttribute iedModel_CTRL_SIMG8_Pres_q;
extern DataAttribute iedModel_CTRL_SIMG8_Pres_t;
extern DataObject    iedModel_CTRL_SIMG8_PresAlm;
extern DataAttribute iedModel_CTRL_SIMG8_PresAlm_stVal;
extern DataAttribute iedModel_CTRL_SIMG8_PresAlm_q;
extern DataAttribute iedModel_CTRL_SIMG8_PresAlm_t;



#define IEDMODEL_CTRL (&iedModel_CTRL)
#define IEDMODEL_CTRL_SIMG1 (&iedModel_CTRL_SIMG1)
#define IEDMODEL_CTRL_SIMG1_Beh (&iedModel_CTRL_SIMG1_Beh)
#define IEDMODEL_CTRL_SIMG1_Beh_stVal (&iedModel_CTRL_SIMG1_Beh_stVal)
#define IEDMODEL_CTRL_SIMG1_Beh_q (&iedModel_CTRL_SIMG1_Beh_q)
#define IEDMODEL_CTRL_SIMG1_Beh_t (&iedModel_CTRL_SIMG1_Beh_t)
#define IEDMODEL_CTRL_SIMG1_InsAlm (&iedModel_CTRL_SIMG1_InsAlm)
#define IEDMODEL_CTRL_SIMG1_InsAlm_stVal (&iedModel_CTRL_SIMG1_InsAlm_stVal)
#define IEDMODEL_CTRL_SIMG1_InsAlm_q (&iedModel_CTRL_SIMG1_InsAlm_q)
#define IEDMODEL_CTRL_SIMG1_InsAlm_t (&iedModel_CTRL_SIMG1_InsAlm_t)
#define IEDMODEL_CTRL_SIMG1_Pres (&iedModel_CTRL_SIMG1_Pres)
#define IEDMODEL_CTRL_SIMG1_Pres_mag (&iedModel_CTRL_SIMG1_Pres_mag)
#define IEDMODEL_CTRL_SIMG1_Pres_mag_f (&iedModel_CTRL_SIMG1_Pres_mag_f)
#define IEDMODEL_CTRL_SIMG1_Pres_q (&iedModel_CTRL_SIMG1_Pres_q)
#define IEDMODEL_CTRL_SIMG1_Pres_t (&iedModel_CTRL_SIMG1_Pres_t)
#define IEDMODEL_CTRL_SIMG1_PresAlm (&iedModel_CTRL_SIMG1_PresAlm)
#define IEDMODEL_CTRL_SIMG1_PresAlm_stVal (&iedModel_CTRL_SIMG1_PresAlm_stVal)
#define IEDMODEL_CTRL_SIMG1_PresAlm_q (&iedModel_CTRL_SIMG1_PresAlm_q)
#define IEDMODEL_CTRL_SIMG1_PresAlm_t (&iedModel_CTRL_SIMG1_PresAlm_t)
#define IEDMODEL_CTRL_SIMG2 (&iedModel_CTRL_SIMG2)
#define IEDMODEL_CTRL_SIMG2_Beh (&iedModel_CTRL_SIMG2_Beh)
#define IEDMODEL_CTRL_SIMG2_Beh_stVal (&iedModel_CTRL_SIMG2_Beh_stVal)
#define IEDMODEL_CTRL_SIMG2_Beh_q (&iedModel_CTRL_SIMG2_Beh_q)
#define IEDMODEL_CTRL_SIMG2_Beh_t (&iedModel_CTRL_SIMG2_Beh_t)
#define IEDMODEL_CTRL_SIMG2_InsAlm (&iedModel_CTRL_SIMG2_InsAlm)
#define IEDMODEL_CTRL_SIMG2_InsAlm_stVal (&iedModel_CTRL_SIMG2_InsAlm_stVal)
#define IEDMODEL_CTRL_SIMG2_InsAlm_q (&iedModel_CTRL_SIMG2_InsAlm_q)
#define IEDMODEL_CTRL_SIMG2_InsAlm_t (&iedModel_CTRL_SIMG2_InsAlm_t)
#define IEDMODEL_CTRL_SIMG2_Pres (&iedModel_CTRL_SIMG2_Pres)
#define IEDMODEL_CTRL_SIMG2_Pres_mag (&iedModel_CTRL_SIMG2_Pres_mag)
#define IEDMODEL_CTRL_SIMG2_Pres_mag_f (&iedModel_CTRL_SIMG2_Pres_mag_f)
#define IEDMODEL_CTRL_SIMG2_Pres_q (&iedModel_CTRL_SIMG2_Pres_q)
#define IEDMODEL_CTRL_SIMG2_Pres_t (&iedModel_CTRL_SIMG2_Pres_t)
#define IEDMODEL_CTRL_SIMG2_PresAlm (&iedModel_CTRL_SIMG2_PresAlm)
#define IEDMODEL_CTRL_SIMG2_PresAlm_stVal (&iedModel_CTRL_SIMG2_PresAlm_stVal)
#define IEDMODEL_CTRL_SIMG2_PresAlm_q (&iedModel_CTRL_SIMG2_PresAlm_q)
#define IEDMODEL_CTRL_SIMG2_PresAlm_t (&iedModel_CTRL_SIMG2_PresAlm_t)
#define IEDMODEL_CTRL_SIMG3 (&iedModel_CTRL_SIMG3)
#define IEDMODEL_CTRL_SIMG3_Beh (&iedModel_CTRL_SIMG3_Beh)
#define IEDMODEL_CTRL_SIMG3_Beh_stVal (&iedModel_CTRL_SIMG3_Beh_stVal)
#define IEDMODEL_CTRL_SIMG3_Beh_q (&iedModel_CTRL_SIMG3_Beh_q)
#define IEDMODEL_CTRL_SIMG3_Beh_t (&iedModel_CTRL_SIMG3_Beh_t)
#define IEDMODEL_CTRL_SIMG3_InsAlm (&iedModel_CTRL_SIMG3_InsAlm)
#define IEDMODEL_CTRL_SIMG3_InsAlm_stVal (&iedModel_CTRL_SIMG3_InsAlm_stVal)
#define IEDMODEL_CTRL_SIMG3_InsAlm_q (&iedModel_CTRL_SIMG3_InsAlm_q)
#define IEDMODEL_CTRL_SIMG3_InsAlm_t (&iedModel_CTRL_SIMG3_InsAlm_t)
#define IEDMODEL_CTRL_SIMG3_Pres (&iedModel_CTRL_SIMG3_Pres)
#define IEDMODEL_CTRL_SIMG3_Pres_mag (&iedModel_CTRL_SIMG3_Pres_mag)
#define IEDMODEL_CTRL_SIMG3_Pres_mag_f (&iedModel_CTRL_SIMG3_Pres_mag_f)
#define IEDMODEL_CTRL_SIMG3_Pres_q (&iedModel_CTRL_SIMG3_Pres_q)
#define IEDMODEL_CTRL_SIMG3_Pres_t (&iedModel_CTRL_SIMG3_Pres_t)
#define IEDMODEL_CTRL_SIMG3_PresAlm (&iedModel_CTRL_SIMG3_PresAlm)
#define IEDMODEL_CTRL_SIMG3_PresAlm_stVal (&iedModel_CTRL_SIMG3_PresAlm_stVal)
#define IEDMODEL_CTRL_SIMG3_PresAlm_q (&iedModel_CTRL_SIMG3_PresAlm_q)
#define IEDMODEL_CTRL_SIMG3_PresAlm_t (&iedModel_CTRL_SIMG3_PresAlm_t)
#define IEDMODEL_CTRL_SIMG4 (&iedModel_CTRL_SIMG4)
#define IEDMODEL_CTRL_SIMG4_Beh (&iedModel_CTRL_SIMG4_Beh)
#define IEDMODEL_CTRL_SIMG4_Beh_stVal (&iedModel_CTRL_SIMG4_Beh_stVal)
#define IEDMODEL_CTRL_SIMG4_Beh_q (&iedModel_CTRL_SIMG4_Beh_q)
#define IEDMODEL_CTRL_SIMG4_Beh_t (&iedModel_CTRL_SIMG4_Beh_t)
#define IEDMODEL_CTRL_SIMG4_InsAlm (&iedModel_CTRL_SIMG4_InsAlm)
#define IEDMODEL_CTRL_SIMG4_InsAlm_stVal (&iedModel_CTRL_SIMG4_InsAlm_stVal)
#define IEDMODEL_CTRL_SIMG4_InsAlm_q (&iedModel_CTRL_SIMG4_InsAlm_q)
#define IEDMODEL_CTRL_SIMG4_InsAlm_t (&iedModel_CTRL_SIMG4_InsAlm_t)
#define IEDMODEL_CTRL_SIMG4_Pres (&iedModel_CTRL_SIMG4_Pres)
#define IEDMODEL_CTRL_SIMG4_Pres_mag (&iedModel_CTRL_SIMG4_Pres_mag)
#define IEDMODEL_CTRL_SIMG4_Pres_mag_f (&iedModel_CTRL_SIMG4_Pres_mag_f)
#define IEDMODEL_CTRL_SIMG4_Pres_q (&iedModel_CTRL_SIMG4_Pres_q)
#define IEDMODEL_CTRL_SIMG4_Pres_t (&iedModel_CTRL_SIMG4_Pres_t)
#define IEDMODEL_CTRL_SIMG4_PresAlm (&iedModel_CTRL_SIMG4_PresAlm)
#define IEDMODEL_CTRL_SIMG4_PresAlm_stVal (&iedModel_CTRL_SIMG4_PresAlm_stVal)
#define IEDMODEL_CTRL_SIMG4_PresAlm_q (&iedModel_CTRL_SIMG4_PresAlm_q)
#define IEDMODEL_CTRL_SIMG4_PresAlm_t (&iedModel_CTRL_SIMG4_PresAlm_t)
#define IEDMODEL_CTRL_SIMG5 (&iedModel_CTRL_SIMG5)
#define IEDMODEL_CTRL_SIMG5_Beh (&iedModel_CTRL_SIMG5_Beh)
#define IEDMODEL_CTRL_SIMG5_Beh_stVal (&iedModel_CTRL_SIMG5_Beh_stVal)
#define IEDMODEL_CTRL_SIMG5_Beh_q (&iedModel_CTRL_SIMG5_Beh_q)
#define IEDMODEL_CTRL_SIMG5_Beh_t (&iedModel_CTRL_SIMG5_Beh_t)
#define IEDMODEL_CTRL_SIMG5_InsAlm (&iedModel_CTRL_SIMG5_InsAlm)
#define IEDMODEL_CTRL_SIMG5_InsAlm_stVal (&iedModel_CTRL_SIMG5_InsAlm_stVal)
#define IEDMODEL_CTRL_SIMG5_InsAlm_q (&iedModel_CTRL_SIMG5_InsAlm_q)
#define IEDMODEL_CTRL_SIMG5_InsAlm_t (&iedModel_CTRL_SIMG5_InsAlm_t)
#define IEDMODEL_CTRL_SIMG5_Pres (&iedModel_CTRL_SIMG5_Pres)
#define IEDMODEL_CTRL_SIMG5_Pres_mag (&iedModel_CTRL_SIMG5_Pres_mag)
#define IEDMODEL_CTRL_SIMG5_Pres_mag_f (&iedModel_CTRL_SIMG5_Pres_mag_f)
#define IEDMODEL_CTRL_SIMG5_Pres_q (&iedModel_CTRL_SIMG5_Pres_q)
#define IEDMODEL_CTRL_SIMG5_Pres_t (&iedModel_CTRL_SIMG5_Pres_t)
#define IEDMODEL_CTRL_SIMG5_PresAlm (&iedModel_CTRL_SIMG5_PresAlm)
#define IEDMODEL_CTRL_SIMG5_PresAlm_stVal (&iedModel_CTRL_SIMG5_PresAlm_stVal)
#define IEDMODEL_CTRL_SIMG5_PresAlm_q (&iedModel_CTRL_SIMG5_PresAlm_q)
#define IEDMODEL_CTRL_SIMG5_PresAlm_t (&iedModel_CTRL_SIMG5_PresAlm_t)
#define IEDMODEL_CTRL_SIMG6 (&iedModel_CTRL_SIMG6)
#define IEDMODEL_CTRL_SIMG6_Beh (&iedModel_CTRL_SIMG6_Beh)
#define IEDMODEL_CTRL_SIMG6_Beh_stVal (&iedModel_CTRL_SIMG6_Beh_stVal)
#define IEDMODEL_CTRL_SIMG6_Beh_q (&iedModel_CTRL_SIMG6_Beh_q)
#define IEDMODEL_CTRL_SIMG6_Beh_t (&iedModel_CTRL_SIMG6_Beh_t)
#define IEDMODEL_CTRL_SIMG6_InsAlm (&iedModel_CTRL_SIMG6_InsAlm)
#define IEDMODEL_CTRL_SIMG6_InsAlm_stVal (&iedModel_CTRL_SIMG6_InsAlm_stVal)
#define IEDMODEL_CTRL_SIMG6_InsAlm_q (&iedModel_CTRL_SIMG6_InsAlm_q)
#define IEDMODEL_CTRL_SIMG6_InsAlm_t (&iedModel_CTRL_SIMG6_InsAlm_t)
#define IEDMODEL_CTRL_SIMG6_Pres (&iedModel_CTRL_SIMG6_Pres)
#define IEDMODEL_CTRL_SIMG6_Pres_mag (&iedModel_CTRL_SIMG6_Pres_mag)
#define IEDMODEL_CTRL_SIMG6_Pres_mag_f (&iedModel_CTRL_SIMG6_Pres_mag_f)
#define IEDMODEL_CTRL_SIMG6_Pres_q (&iedModel_CTRL_SIMG6_Pres_q)
#define IEDMODEL_CTRL_SIMG6_Pres_t (&iedModel_CTRL_SIMG6_Pres_t)
#define IEDMODEL_CTRL_SIMG6_PresAlm (&iedModel_CTRL_SIMG6_PresAlm)
#define IEDMODEL_CTRL_SIMG6_PresAlm_stVal (&iedModel_CTRL_SIMG6_PresAlm_stVal)
#define IEDMODEL_CTRL_SIMG6_PresAlm_q (&iedModel_CTRL_SIMG6_PresAlm_q)
#define IEDMODEL_CTRL_SIMG6_PresAlm_t (&iedModel_CTRL_SIMG6_PresAlm_t)
#define IEDMODEL_CTRL_SIMG7 (&iedModel_CTRL_SIMG7)
#define IEDMODEL_CTRL_SIMG7_Beh (&iedModel_CTRL_SIMG7_Beh)
#define IEDMODEL_CTRL_SIMG7_Beh_stVal (&iedModel_CTRL_SIMG7_Beh_stVal)
#define IEDMODEL_CTRL_SIMG7_Beh_q (&iedModel_CTRL_SIMG7_Beh_q)
#define IEDMODEL_CTRL_SIMG7_Beh_t (&iedModel_CTRL_SIMG7_Beh_t)
#define IEDMODEL_CTRL_SIMG7_InsAlm (&iedModel_CTRL_SIMG7_InsAlm)
#define IEDMODEL_CTRL_SIMG7_InsAlm_stVal (&iedModel_CTRL_SIMG7_InsAlm_stVal)
#define IEDMODEL_CTRL_SIMG7_InsAlm_q (&iedModel_CTRL_SIMG7_InsAlm_q)
#define IEDMODEL_CTRL_SIMG7_InsAlm_t (&iedModel_CTRL_SIMG7_InsAlm_t)
#define IEDMODEL_CTRL_SIMG7_Pres (&iedModel_CTRL_SIMG7_Pres)
#define IEDMODEL_CTRL_SIMG7_Pres_mag (&iedModel_CTRL_SIMG7_Pres_mag)
#define IEDMODEL_CTRL_SIMG7_Pres_mag_f (&iedModel_CTRL_SIMG7_Pres_mag_f)
#define IEDMODEL_CTRL_SIMG7_Pres_q (&iedModel_CTRL_SIMG7_Pres_q)
#define IEDMODEL_CTRL_SIMG7_Pres_t (&iedModel_CTRL_SIMG7_Pres_t)
#define IEDMODEL_CTRL_SIMG7_PresAlm (&iedModel_CTRL_SIMG7_PresAlm)
#define IEDMODEL_CTRL_SIMG7_PresAlm_stVal (&iedModel_CTRL_SIMG7_PresAlm_stVal)
#define IEDMODEL_CTRL_SIMG7_PresAlm_q (&iedModel_CTRL_SIMG7_PresAlm_q)
#define IEDMODEL_CTRL_SIMG7_PresAlm_t (&iedModel_CTRL_SIMG7_PresAlm_t)
#define IEDMODEL_CTRL_SIMG8 (&iedModel_CTRL_SIMG8)
#define IEDMODEL_CTRL_SIMG8_Beh (&iedModel_CTRL_SIMG8_Beh)
#define IEDMODEL_CTRL_SIMG8_Beh_stVal (&iedModel_CTRL_SIMG8_Beh_stVal)
#define IEDMODEL_CTRL_SIMG8_Beh_q (&iedModel_CTRL_SIMG8_Beh_q)
#define IEDMODEL_CTRL_SIMG8_Beh_t (&iedModel_CTRL_SIMG8_Beh_t)
#define IEDMODEL_CTRL_SIMG8_InsAlm (&iedModel_CTRL_SIMG8_InsAlm)
#define IEDMODEL_CTRL_SIMG8_InsAlm_stVal (&iedModel_CTRL_SIMG8_InsAlm_stVal)
#define IEDMODEL_CTRL_SIMG8_InsAlm_q (&iedModel_CTRL_SIMG8_InsAlm_q)
#define IEDMODEL_CTRL_SIMG8_InsAlm_t (&iedModel_CTRL_SIMG8_InsAlm_t)
#define IEDMODEL_CTRL_SIMG8_Pres (&iedModel_CTRL_SIMG8_Pres)
#define IEDMODEL_CTRL_SIMG8_Pres_mag (&iedModel_CTRL_SIMG8_Pres_mag)
#define IEDMODEL_CTRL_SIMG8_Pres_mag_f (&iedModel_CTRL_SIMG8_Pres_mag_f)
#define IEDMODEL_CTRL_SIMG8_Pres_q (&iedModel_CTRL_SIMG8_Pres_q)
#define IEDMODEL_CTRL_SIMG8_Pres_t (&iedModel_CTRL_SIMG8_Pres_t)
#define IEDMODEL_CTRL_SIMG8_PresAlm (&iedModel_CTRL_SIMG8_PresAlm)
#define IEDMODEL_CTRL_SIMG8_PresAlm_stVal (&iedModel_CTRL_SIMG8_PresAlm_stVal)
#define IEDMODEL_CTRL_SIMG8_PresAlm_q (&iedModel_CTRL_SIMG8_PresAlm_q)
#define IEDMODEL_CTRL_SIMG8_PresAlm_t (&iedModel_CTRL_SIMG8_PresAlm_t)

#endif /* STATIC_MODEL_H_ */

